name: Sync App Script Guide from Google Doc

on:
  schedule:
    - cron: '0 */6 * * *'  # Runs every 6 hours
  workflow_dispatch:  # Allows manual triggering

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install google-api-python-client google-auth-httplib2 google-auth-oauthlib google-auth requests markdown2

      - name: Create OAuth credentials file
        run: |
          echo '${{ secrets.GOOGLE_OAUTH_CREDENTIALS }}' | jq '.' > credentials.json

      - name: Sync App Script Guide
        env:
          DOCUMENT_ID: "1kftsY9KZa27xBzZ7189bu1S2Fqd1bVfXec4VHZNlXcs"
          GOOGLE_REFRESH_TOKEN: ${{ secrets.GOOGLE_REFRESH_TOKEN }}
        run: |
          python .github/scripts/sync_readme.py
        
      - name: Commit and push if changed
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions"
          git add README.md
          git diff --quiet && git diff --staged --quiet || (git commit -m "docs: sync README from Google Docs" && git push)
